<?php
/**
 * Message translations.
 *
 * This file is manually generated by leo !
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adresse' => 'Address',
    'Choisir une valeur' => 'Choose a value',
    'Conditions inscription et annulation' => '<h4>Registration and cancellation conditions</h4>
    Registration for climbing courses is by reservation. No cancellation fees are charged up to 7 days before the course
    start date. Within 7 days before the course start date, 25% of the total amount is charged for regular seasonal
    courses and 40% of the total amount is charged for all other courses. From the date of the first course, 100% of the
    amount is due.<br />
    <br />
    Vertic-Halle does not refund any amounts due under the above-mentioned conditions, nor does it refund any partial
    amounts for missed classes (except for the portion relating to admission and materials, if applicable). In the event
    of cancellation by Vertic-Halle, the amount already paid will be refunded in proportion to the canceled classes.<br />
    <br />
    Vertic-Halle reserves the right to modify the service depending on the level and number of participants, if
    conditions allow and the course objectives can be achieved.',
    'Date de naissance participant.e' => 'Participant date of birth',
    'En cochant cette case je déclare avoir lu et accepté les conditions d\'inscription et d\'annulation indiquées au bas de cette page' => 'By ticking this box I declare that I have read and accept the registration and cancellation conditions indicated at the bottom of this page.',
    'Fk Cours' => 'Course name',
    'Infos, détails et besoins particuliers' => 'Information, Details and special needs',
    'J\'aimerais que mon enfant essaie avant de l\'inscrire pour la saison et je souhaite être contacté à ce sujet' => 'I would like my child to try out before registering them for the season and I would like to be contacted about this',
    'Langue maternelle' => 'Native language',
    'Localite' => 'Locality',
    'Nationalité' => 'Nationality',
    'No AVS participant.e' => 'Participant AVS number',
    'nom du cours' => 'Course name',
    'Nom du représentant légal (si mineur.e)' => 'Name of legal representative (if a minor)',
    'Nom participant.e' => 'Participant name',
    'Nous avons bien reçu votre commande.<br>Un mail de confirmation de réception de celle-ci vous a été envoyé par e-mail.' => 'We have received your order.<br>A confirmation email has been sent to you',
    'Npa' => 'Postcode',
    'Numéro' => 'Number',
    'Paiement du cours en un seul versement' => 'Payment in one instalment',
    'Paiement du cours en plusieurs versements (+ CHF 40 de frais administratifs)' => 'Payment in various instalments (+40 CHF)',
    'Pays' => 'Country',
    'Prénom du représentant légal (si mineur.e)' => 'First name of legal representative (if a minor)',
    'Prénom participant.e' => 'Participant first name',
    'S\'inscrire' => 'Register',
    'Sexe' => 'Gender',
    'Telephone' => 'Phone number',
    'Une erreur est survenue lors de l\'enregistrement.' => 'An error occurred while saving.',
];
